services:
  - type: web
    name: kol-insight-collection-h5
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm run start -- -H 0.0.0.0 -p $PORT
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATA_DIR
        value: data
